server:
  port: 8301
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.149.141.81:3306/cloudstudy
    username: test
    password: P@ssW0rd
  application:
    name: borrow-service
  cloud:
    nacos:
      discovery:
        # 配置Nacos注册中心地址
        server-addr: localhost:8848
        # 将ephemeral修改为false，表示非临时实例
        ephemeral: false
        cluster-name: Chengdu
        namespace: 7bae848b-6745-4d48-be55-3e868569394e
    loadbalancer:
      nacos:
        enabled: true