spring:
  cloud:
    nacos:
      discovery:
        # 配置Nacos注册中心地址
        server-addr: localhost:8848
seata:
  # 注册
  registry:
    # 使用Nacos
    type: nacos
    nacos:
      # 使用Seata的命名空间，这样才能正确找到Seata服务，由于组使用的是SEATA_GROUP，配置默认值就是，就不用配了
      namespace: 4dc1823b-5f47-4ac5-af66-4f18a2edb1c2
      username: nacos
      password: nacos
  # 配置
  config:
    type: nacos
    nacos:
      namespace: 4dc1823b-5f47-4ac5-af66-4f18a2edb1c2
      username: nacos
      password: nacos